<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FinalEngine.Audio</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="KinsonDigital.CASL" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\FinalEngine\FinalEngine.csproj" />
  </ItemGroup>
</Project>
