<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExampleGame\ExampleGame.csproj" />
    <ProjectReference Include="..\FinalEngine.Audio.OpenAL\FinalEngine.Audio.CASL.csproj" />
    <ProjectReference Include="..\FinalEngine.Hosting\FinalEngine.Hosting.csproj" />
    <ProjectReference Include="..\FinalEngine.Platform.Desktop\FinalEngine.Platform.Desktop.csproj" />
    <ProjectReference Include="..\FinalEngine.Rendering.OpenGL\FinalEngine.Rendering.OpenGL.csproj" />
    <ProjectReference Include="..\FinalEngine\FinalEngine.csproj" />
  </ItemGroup>

</Project>
