<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FinalEngine.Decoding.Imaging</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinalEngine\FinalEngine.csproj" />
  </ItemGroup>

</Project>
