<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <NoWarn>SA0001</NoWarn>
    <UseWPF>true</UseWPF>
    <AnalysisMode>All</AnalysisMode>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\Icons\Settings.png" />
    <None Remove="Resources\Images\Splashes\splash.png" />
  </ItemGroup>
  
  <ItemGroup>
    <AdditionalFiles Include="..\Styling\StyleCop\Other\stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
    <Compile Include="..\SharedAssemblyInfo.cs" Link="Properties\SharedAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.72.1" />
    <PackageReference Include="EventBinder" Version="2.5.3" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.6" />
    <PackageReference Include="OpenTK.GLWpfControl" Version="4.3.3" />
    <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Twizzle.ImGuizmo.NET" Version="1.89.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinalEngine.Audio.OpenAL\FinalEngine.Audio.OpenAL.csproj" />
    <ProjectReference Include="..\FinalEngine.Editor.ViewModels\FinalEngine.Editor.ViewModels.csproj" />
    <ProjectReference Include="..\FinalEngine.Rendering.OpenGL\FinalEngine.Rendering.OpenGL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\Icons\Settings.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="Resources\Images\Splashes\splash.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Layouts\default.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
