<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Rendering\Resources\Shaders\Batching\sprite-geometry.fesp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Resources\Shaders\Batching\sprite-geometry.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Resources\Shaders\Batching\sprite-geometry.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
