<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="[9.0.0,)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="[9.0.6,)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[9.0.6,)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="[9.0.6,)" />
    <PackageVersion Include="KinsonDigital.CASL" Version="[1.0.0-preview.21,)" />
    <PackageVersion Include="System.IO.Abstractions" Version="21.3.1" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="[3.1.10,)" />
    <PackageVersion Include="OpenTK" Version="[4.8.2,)" />
    <PackageVersion Include="AutoMapper.Extensions.EnumMapping" Version="[4.1.0,)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="[9.0.5,)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="[9.0.5,)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.EventLog" Version="[9.0.5,)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.EventSource" Version="[9.0.5,)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="[9.0.5,)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="[9.0.5,)" />
  </ItemGroup>
</Project>