<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FinalEngine.Platform</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
	  <PackageReference Include="OpenTK" />
	</ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\FinalEngine\FinalEngine.csproj" />
  </ItemGroup>
</Project>
