name: ✅ Build Status Check
run-name: ✅ Build Status Check (${{ github.base_ref }} branch)

on:
    push:
      branches: [ "final" ]
    pull_request:
      branches: [ "final" ]

jobs:

  # FinalEngine
  build_core:
    name: Core
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore FinalEngine/FinalEngine.csproj

      - name: Build
        run: dotnet build FinalEngine/FinalEngine.csproj --no-restore --configuration Debug

  # FinalEngine.Hosting
  build_hosting:
    name: Hosting
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore FinalEngine.Hosting/FinalEngine.Hosting.csproj

      - name: Build
        run: dotnet build FinalEngine.Hosting/FinalEngine.Hosting.csproj --no-restore --configuration Debug

  # FinalEngine.Platform.Desktop
  build_platform_desktop:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore FinalEngine.Platform.Desktop/FinalEngine.Platform.Desktop.csproj

      - name: Build
        run: dotnet build FinalEngine.Platform.Desktop/FinalEngine.Platform.Desktop.csproj --no-restore --configuration Debug