name: 🚀 Release
run-name: 🚀 ${{ github.ref_name }} Release

on:
  push:
    tags:
      - 'v*'

jobs:
  set_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - id: get_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

  # FinalEngine
  build_core:
    name: Build Core
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore FinalEngine/FinalEngine.csproj

      - name: Build
        run: dotnet build FinalEngine/FinalEngine.csproj --no-restore --configuration Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FinalEngine
          path: FinalEngine/bin/Release/net9.0/

  # FinalEngine.Hosting
  build_hosting:
    name: Build Hosting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore FinalEngine.Hosting/FinalEngine.Hosting.csproj

      - name: Build
        run: dotnet build FinalEngine.Hosting/FinalEngine.Hosting.csproj --no-restore --configuration Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FinalEngine.Hosting
          path: FinalEngine.Hosting/bin/Release/net9.0/

  # FinalEngine.Platform.Desktop
  build_platform_desktop:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore FinalEngine.Platform.Desktop/FinalEngine.Platform.Desktop.csproj

      - name: Build
        run: dotnet build FinalEngine.Platform.Desktop/FinalEngine.Platform.Desktop.csproj --no-restore --configuration Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FinalEngine.Platform.Desktop
          path: FinalEngine.Platform.Desktop/bin/Release/net9.0-windows/

  # Release
  release:
    name: Create GitHub Release
    needs: [build_core, build_hosting, build_platform_desktop]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download Core artifacts
        uses: actions/download-artifact@v4
        with:
          name: FinalEngine
          path: artifacts/FinalEngine

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: FinalEngine.Platform.Desktop
          path: artifacts/FinalEngine.Platform.Desktop

      - name: Download Hosting artifacts
        uses: actions/download-artifact@v4
        with:
          name: FinalEngine.Hosting
          path: artifacts/FinalEngine.Hosting

      - name: Zip artifacts
        run: |
          cd artifacts
          zip -r FinalEngine.zip FinalEngine
          zip -r FinalEngine.Platform.Desktop.zip FinalEngine.Platform.Desktop
          zip -r FinalEngine.Hosting.zip FinalEngine.Hosting

      - name: Extract version
        id: kacl
        uses: zogot/kacl-parser@1.0.0
        with:
          version: ${{ github.ref_name }}
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.kacl.outputs.release }}
          files: |
            artifacts/FinalEngine.zip
            artifacts/FinalEngine.Platform.Desktop.zip
            artifacts/FinalEngine.Hosting.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
